openapi: 3.0.0
info:
  title: broker_app
  version: v1
  description: ''
servers:
  - url: 'https://services.utelly.com/broker_app/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/broker_app/v1'
    description: staging
  - url: 'https://dev-services.utelly.com/broker_app/v1'
    description: dev
paths:
  /user/login:
    post:
      summary: Login
      operationId: v1.user.login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                required:
                  - id
                  - access_token
                  - refresh_token
              examples:
                '1':
                  value:
                    id: 9b38b54dd74644db96e772d6076615da
                    access_token: 9b38b54dd74644db96e772d6076615da
                    refresh_token: f9a664c1ba3f4665aa902ded47edaca9
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
            examples:
              '1':
                value:
                  email: hello@utelly.com
                  password: 3@Ubc1iCYZUKGtAi
      tags:
        - User Management
    parameters: []
  /user/refresh_jwt_access_token:
    post:
      summary: Refresh JWT access_token
      operationId: v1.user.refresh_jwt_access_token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                required:
                  - access_token
              examples:
                '1':
                  value:
                    access_token: f9a664c1ba3f4665aa902ded47edaca9
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
              required:
                - refresh_token
            examples:
              '1':
                value:
                  refresh_token: cc53ca4aaf294c489a29c1515cb1f1b3
      description: ''
      tags:
        - User Management
    parameters: []
  /user/register:
    post:
      summary: Register
      operationId: v1.user.register
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                required:
                  - id
                  - access_token
                  - refresh_token
              examples:
                '1':
                  value:
                    id: 9b38b54dd74644db96e772d6076615da
                    access_token: 9b38b54dd74644db96e772d6076615da
                    refresh_token: f9a664c1ba3f4665aa902ded47edaca9
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                registration_token:
                  type: string
                password:
                  type: string
                password_confirm:
                  type: string
                destination_url_template:
                  type: string
              required:
                - first_name
                - last_name
                - email
                - registration_token
                - password
                - password_confirm
                - destination_url_template
            examples:
              '1':
                value:
                  first_name: Keizer
                  last_name: SÃ¶ze
                  email: keizer@email.com
                  registration_token: 55a68d8af89b4a29a453c9a21b37445f
                  password: password
                  password_confirm: password
                  destination_url_template: 'https://mydomain.com/confirm?user_id={user_id}&code={code}'
      tags:
        - User Management
    parameters: []
  /user/forgot_password:
    post:
      summary: Forgot password
      operationId: v1.user.forgot_password
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                destination_url_template:
                  type: string
              required:
                - email
                - destination_url_template
            examples:
              '1':
                value:
                  email: keizer@email.com
                  destination_url_template: 'https://mydomain.com/forgot_password_page?email={email}&token={token}'
      description: sends an email with a authentication token
      tags:
        - User Management
    parameters: []
  /user/email_confirm:
    post:
      summary: Confirm email
      operationId: v1.user.confirm
      responses:
        '200':
          description: OK
      description: validates user email
      parameters: []
      tags:
        - User Management
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                code:
                  type: string
            examples:
              '1':
                value:
                  user_id: 9b38b54dd74644db96e772d6076615da
                  code: 06ebadbe3bbf4e2798fd421b1346c1ee
    parameters: []
  /user/preferences:
    parameters: []
    get:
      summary: Get preferences
      operationId: v1.user.get_preferences
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  values:
                    type: array
                    items:
                      $ref: ../models/kv_field.v1.yaml
              examples:
                '1':
                  value:
                    values:
                      - key: default_env
                        value: '1'
                      - key: default_perspective
                        value: '1'
                      - key: default_view
                        value: '1'
      security:
        - Authorization: []
      description: ''
      tags:
        - User Management
  /ui/layout:
    parameters: []
    get:
      summary: Get ui layout
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                Default:
                  value:
                    enviroments:
                      - uid: '1'
                        names:
                          en: Development
                          nl: Ontwikkeling
                        descriptions:
                          en: Use and make things to break them
                          nl: Gebruik en maak dingen om ze te breken
                      - uid: '2'
                        names:
                          en: Staging
                          nl: Enscenering
                        descriptions:
                          en: Use to see if things break
                          nl: Gebruik om te zien of dingen breken
                      - uid: '3'
                        names:
                          en: Production
                          nl: Productie
                        descriptions:
                          en: Final working version
                          nl: Definitieve werkende versie
                    perspectives:
                      - uid: '1'
                        names:
                          en: Architect
                          nl: Architect
                        descriptions:
                          en: Example description
                          nl: Voorbeeldbeschrijving
                        base_url: /architect
                        navigation:
                          - uid: '1'
                            names:
                              en: Data Sources
                              nl: Data Bronnen
                            href: /data-sources
                          - uid: '2'
                            names:
                              en: Data Flows
                              nl: Gegevensstromen
                            href: /data-flows
                      - uid: '2'
                        names:
                          en: Operate
                          nl: Bedienen
                        descriptions:
                          en: Example description
                          nl: Voorbeeldbeschrijving
                        base_url: /operate
                        navigation: []
                      - uid: '3'
                        names:
                          en: Promote
                          nl: Promoten
                        descriptions:
                          en: Example description
                          nl: Voorbeeldbeschrijving
                        base_url: /promote
                        navigation: []
                      - uid: '4'
                        names:
                          en: Analyse
                          nl: Analyse
                        descriptions:
                          en: Example description
                          nl: Voorbeeldbeschrijving
                        base_url: /analyse
                        navigation: []
                    preferences:
                      default_enviroment: '1'
                      selected_enviroment: '2'
                      default_perspective: '1'
                      selected_perspective: '1'
                      default_perspective_navigation: '1'
                      selected_perspective_navigation: '1'
                      default_language: en
                      selected_language: nl
      operationId: v1.ui.get_layout
      security:
        - Authorization: []
      description: ''
      tags:
        - UI
  '/configurations/environment/{environment_id}/view/{view_id}':
    get:
      summary: Get configurations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  configurations:
                    type: array
                    items:
                      $ref: ../models/Configuration.v1.yaml
              examples:
                '1':
                  value:
                    configurations:
                      - id: '1'
                        name:
                          - locale: en
                            value: friendly name of the conf
                        payload: {}
                      - id: '2'
                        name:
                          - locale: en
                            value: friendly name of the conf2
                        payload: {}
      operationId: v1.configuration.get
      description: ''
      security:
        - Authorization: []
      tags:
        - Configuration Management
    parameters:
      - schema:
          type: string
        name: environment_id
        in: path
        required: true
      - schema:
          type: string
        name: view_id
        in: path
        required: true
  /user/forgot_password_confirm:
    post:
      summary: Forgot password confirm
      operationId: v1.user.forgot_password_confirm
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                token:
                  type: string
                password:
                  type: string
                password_confirm:
                  type: string
            examples:
              '1':
                value:
                  email: keizer@email.com
                  token: 3c5ace8b39354d54aaefec5c7c35da76
                  password: password
                  password_confirm: password
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  access_token:
                    type: string
                  refresh_token:
                    type: string
              examples:
                '1':
                  value:
                    id: 4546ed7dd9ed477ba368749f0bd8b3a1
                    access_token: eb1b44a9977c44e1a880df4637efec4a
                    refresh_token: f63034cbebf34f7d852f7ab83a39a1b4
      tags:
        - User Management
components:
  schemas: {}
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
      x-apikeyInfoFunc: security.check_token
