components:
  schemas: {}
  securitySchemes:
    Authorization:
      in: header
      name: Authorization
      type: apiKey
      x-apikeyInfoFunc: security.check_token
info:
  contact:
    email: developers@utelly.com
    name: API Support
  title: configuration_manager
  version: v1
openapi: 3.0.0
paths:
  /configurations/source/{type}:
    get:
      description: 'Retrieve configurations by type directly from the configuration source. Caching disabled for the endpoint. Only accessible by the admin user.'
      operationId: v1.configuration.get_configs
      responses:
        '200':
          content:
            application/json:
              examples:
                '1':
                  value:
                    - config:
                        SHERLOCK_READ_INDEX: sherlock_iva_iva_read
                        default_size: 20
                        depth: '2'
                        display_name: LG Demo
                        enrichments: []
                        entities:
                          - topic
                          - genre
                          - mood
                          - actor
                          - director
                        grouping: entity
                        ids_fields:
                          - source_id
                        languages:
                          - en
                        options:
                          - phonetic
                          - qualifiers
                          - rest
                        source: iva_iva
                      identifier: my identifier
                      type: sherlockConfig
              schema:
                type: array
                items:
                  properties: {}
                  type: object
          description: OK
      summary: Get Configurations
      tags:
        - Configuration Management
      x-internal: true
    post:
      description: 'Create a configuration and store directly in the configuration source. Caching disabled for the endpoint. Only accessible by the admin user.'
      operationId: v1.configuration.create_config
      requestBody:
        content:
          application/json:
            examples:
              '1':
                value:
                  config:
                    SHERLOCK_READ_INDEX: sherlock_iva_iva_read
                    default_size: 20
                    depth: '2'
                    display_name: LG Demo
                    enrichments: []
                    entities:
                      - topic
                      - genre
                      - mood
                      - actor
                      - director
                    grouping: entity
                    ids_fields:
                      - source_id
                    languages:
                      - en
                    options:
                      - phonetic
                      - qualifiers
                      - rest
                    source: iva_iva
                  identifier: my identifier
            schema:
              type: object
              properties: {}
      summary: Create Configuration
      x-internal: True
      responses:
        '201':
          description: OK
    parameters:
    - description: configuration type
      in: path
      name: type
      required: true
      schema:
        type: string  
  /configurations/source/{type}/{identifier}:
    get:
      description: 'Retrieve a configuration directly from the configuration source. Caching disabled for the endpoint. Only accessible by the admin user.'
      operationId: v1.configuration.get_config
      responses:
        '200':
          content:
            application/json:
              examples:
                '1':
                  value:
                    config:
                      SHERLOCK_READ_INDEX: sherlock_iva_iva_read
                      default_size: 20
                      depth: '2'
                      display_name: LG Demo
                      enrichments: []
                      entities:
                        - topic
                        - genre
                        - mood
                        - actor
                        - director
                      grouping: entity
                      ids_fields:
                        - source_id
                      languages:
                        - en
                      options:
                        - phonetic
                        - qualifiers
                        - rest
                      source: iva_iva
                    identifier: my identifier
                    type: sherlockConfig
              schema:
                properties: {}
                type: object
          description: OK
      summary: Get Configurations
      tags:
        - Configuration Management
      x-internal: True
    post:
      description: 'Update a configuration directly in the configuration source. Caching disabled for the endpoint. Only accessible by the admin user.'
      operationId: v1.configuration.update_config
      requestBody:
        content:
          application/json:
            examples:
              '1':
                value:
                  config:
                    SHERLOCK_READ_INDEX: sherlock_iva_iva_read
                    default_size: 20
                    depth: '2'
                    display_name: LG Demo
                    enrichments: []
                    entities:
                      - topic
                      - genre
                      - mood
                      - actor
                      - director
                    grouping: entity
                    ids_fields:
                      - source_id
                    languages:
                      - en
                    options:
                      - phonetic
                      - qualifiers
                      - rest
                    source: iva_iva
            schema:
              type: object
              properties: {}
      summary: Update Configuration
      x-internal: True
      responses:
        '201':
          description: OK
    parameters:
    - description: configuration type
      in: path
      name: type
      required: true
      schema:
        type: string 
    - description: configuration identifier
      in: path
      name: identifier
      required: true
      schema:
        type: string 
  /configurations:
    get:
      description: 'Retrieve a configuration or configurations by type. Caching enabled for the endpoint.'
      operationId: v1.configuration.get
      parameters:
        - in: query
          name: type
          required: true
          schema:
            type: string
        - in: query
          name: identifier
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                '1':
                  value:
                    - config:
                        SHERLOCK_READ_INDEX: sherlock_iva_iva_read
                        default_size: 20
                        depth: '2'
                        display_name: LG Demo
                        enrichments: []
                        entities:
                          - topic
                          - genre
                          - mood
                          - actor
                          - director
                        grouping: entity
                        ids_fields:
                          - source_id
                        languages:
                          - en
                        options:
                          - phonetic
                          - qualifiers
                          - rest
                        source: iva_iva
                      identifier: my identifier
                      type: sherlockConfig
              schema:
                properties: {}
                type: object
          description: OK
      summary: Get Configurations
      tags:
        - Configuration Management
      x-internal: false
  /configurations_update:
    post:
      summary: Update Configurations
      operationId: v1.configuration.update
      responses:
        '200':
          description: OK
    parameters: []
servers:
  - description: prod
    url: 'https://services.utelly.com/configuration_manager/v1'
  - description: staging
    url: 'https://staging-services.utelly.com/configuration_manager/v1'
  - description: dev
    url: 'https://dev-services.utelly.com/configuration_manager/v1'
tags:
  - name: utelly_services
security:
  - Authorization: []
