openapi: 3.0.0
info:
  title: discover_manager
  version: v1
  description: ''
  contact:
    email: developers@utelly.com
    name: API Support
servers:
  - url: 'https://services.utelly.com/discover_manager/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/discover_manager/v1'
    description: staging
  - url: 'https://dev-services.utelly.com/discover_manager/v1'
    description: dev
paths:
  /creative_works/discover:
    get:
      summary: Discover Creative Works
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                additionalProperties: false
                type: object
                properties:
                  _embedded:
                    additionalProperties: false
                    type: object
                    properties:
                      creative_works:
                        type: array
                        items:
                          $ref: ./browse_manager.v1.yaml#/components/schemas/CreativeWork
                  _links:
                    $ref: ../models/HalLinks.v1.yaml
                  discover_guid:
                    type: string
                    description: Discover GUID used for interactions context
                  total_count:
                    type: integer
                    description: Total number of results
                required:
                  - _embedded
                  - _links
                  - discover_guid
                  - total_count
              examples:
                '1':
                  value:
                    _embedded:
                      creative_works:
                        - _links:
                            availabilities:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/availabilities
                            content_ratings:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/content_ratings
                            contributors:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/contributors
                            episodes:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/episodes
                            seasons:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/seasons
                            self:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46
                            tags:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/tags
                          artworks:
                            - height: 100
                              metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: poster
                              url: 'https://mydomain.com/poster.jpg'
                              width: 100
                          created_at: '2020-01-01T00:00:10Z'
                          deleted: false
                          descriptions:
                            - description: 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.'
                              metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: full
                          guid: 27c13eec19014084a0a3173061702b46
                          identifiers:
                            - id: '1'
                              source: mysource
                          relationships:
                            - href: /content/creative_works/eac7cb1192264b088ccbad0874395ce5
                              rel: parent
                          titles:
                            - metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: official
                              title: The Usual Suspects
                          type: movie
                          updated_at: '2020-01-01T00:00:10Z'
                    _links:
                      first:
                        href: /content/creative_works
                      last:
                        href: /content/creative_works?after_guid=8703dd1ced974ecea01116f2c0a5a282&limit=50
                      next:
                        href: /content/creative_works?after_guid=8703dd1ced974ecea01116f2c0a5a282&limit=50
                      prev:
                        href: /content/creative_works
                      self:
                        href: /content/creative_works?after_guid=8703dd1ced974ecea01116f2c0a5a282&limit=50
                    discover_guid: 8703dd1ced974ecea01116f2c0a5a282
                    total_count: 1
      operationId: v1.discover.creative_work.get
      parameters:
        - schema:
            type: array
            items:
              type: string
          in: query
          name: services
          style: pipeDelimited
          explode: true
          description: Has one or more of the listed service ids as an availability.
        - schema:
            type: array
          in: query
          name: 'services[excl]'
          style: pipeDelimited
          explode: true
          description: Has none of the listed service ids as an availability.
        - schema:
            type: array
            items:
              type: string
          in: query
          name: locations
          style: pipeDelimited
          explode: true
          description: Has availability for one or more of the listed location ids.
        - schema:
            type: array
            items:
              type: integer
          in: query
          name: release_year
          style: pipeDelimited
          explode: true
          description: Has one of the listed release years
        - schema:
            type: integer
            items:
              type: integer
            minimum: 1900
          in: query
          name: 'release_year[gte]'
          style: pipeDelimited
          explode: true
          description: Has a release year greater than or equal to values
        - schema:
            type: integer
            items:
              type: integer
            minimum: 1900
          in: query
          name: 'release_year[lte]'
          style: pipeDelimited
          explode: true
          description: Has a release year less than or equal to values
        - schema:
            type: array
            items:
              type: string
          in: query
          name: content_ratings
          style: pipeDelimited
          explode: true
          description: Has one or more of the listed content rating ids
        - schema:
            type: array
            items:
              type: string
          in: query
          name: 'content_ratings[excl]'
          style: pipeDelimited
          explode: true
          description: Has none of the listed content rating ids
        - schema:
            type: array
            items:
              type: string
          in: query
          name: tags
          style: pipeDelimited
          explode: true
          description: Has one of the listed tag ids.
        - schema:
            type: array
            items:
              type: string
          in: query
          name: 'tags[all]'
          style: pipeDelimited
          explode: true
          description: Has all of the listed tag ids.
        - schema:
            type: array
            items:
              type: string
          in: query
          name: 'tags[excl]'
          style: pipeDelimited
          explode: true
          description: Has none of the listed tag ids.
        - schema:
            type: array
            items:
              type: string
            example:
              - movie
              - series
          in: query
          name: types
          style: pipeDelimited
          explode: true
          description: Is one of the listed types
        - schema:
            type: array
            items:
              type: string
          in: query
          name: guids
          style: pipeDelimited
          explode: true
          description: Includes creative works
        - schema:
            type: array
            items:
              type: string
          in: query
          name: 'guids[excl]'
          style: pipeDelimited
          explode: true
          description: Excludes creative works
        - schema:
            type: array
            items:
              type: string
          in: query
          name: titles
          style: pipeDelimited
          explode: true
        - schema:
            type: string
            enum:
              - popularity
              - relevancy
              - release_year
              - recommendation
              - rating
          in: query
          name: order_by
        - schema:
            type: integer
          in: query
          name: refresh_rate
        - schema:
            type: array
            items:
              type: integer
          in: query
          name: title_shuffle_set
          style: pipeDelimited
          explode: true
        - schema:
            type: integer
          in: query
          name: shuffle_rate
        - schema:
            type: integer
            minimum: 0
            maximum: 50
          in: query
          name: limit
        - schema:
            type: integer
            items:
              $ref: ../models/integer_range_field.v1.yaml
          in: query
          name: 'duration[gte]'
          style: pipeDelimited
          explode: true
          description: Has duration greater than or equal to.
        - schema:
            type: integer
            items:
              $ref: ../models/integer_range_field.v1.yaml
          in: query
          name: 'duration[lte]'
          style: pipeDelimited
          explode: true
          description: Has duration less than or equal to.
        - schema:
            type: array
            example:
              - 'actor:eb4aaa3de91242ba82ad48bee0b48996'
          in: query
          name: people
          style: pipeDelimited
          explode: true
          description: Has one or more of the listed people ids as a contributor - optional role flag.
        - schema:
            type: array
          in: query
          name: 'people[all]'
          style: pipeDelimited
          explode: true
          description: Has all of the listed people ids as a contributor - optional role flag.
        - schema:
            type: array
          in: query
          name: 'people[excl]'
          style: pipeDelimited
          explode: true
          description: Has none of the listed people ids as a contributor - optional role flag.
        - schema:
            type: array
            example:
              - 'imdb:80'
              - 'tmdb:75'
          in: query
          name: 'rating[gte]'
          style: pipeDelimited
          description: Has rating greater than or equal to. List of ratings values with source flag
        - schema:
            type: array
            example:
              - 'imdb:80'
              - 'tmdb:75'
          in: query
          name: 'rating[lte]'
          style: pipeDelimited
          description: Has rating less than or equal to. List of ratings values with source flag
        - schema:
            type: string
          in: header
          name: Content-Language
          description: 'Used to remove unnecessary titles, descriptions and artworks. Defaults to en-US'
        - schema:
            type: array
          in: query
          name: artworks_type
          description: List of artwork types to be included in the response.
        - schema:
            type: array
          in: query
          name: fields
          description: List of resource fields to be including in the response.
          style: pipeDelimited
        - schema:
            type: array
            example:
              - availabilities
              - tags
          in: query
          name: embed
          description: 'List of related resources to be embedded in creative works. Note: embedded resources will themselves be fully embedded.'
          style: pipeDelimited
        - schema:
            type: string
          in: query
          name: q
          description: Natural language query string. Will be interpreted by NLU component. Other content filters will be ignored.
        - $ref: '#/components/parameters/user_param'
        - schema:
            type: integer
          in: query
          name: skip
      description: ''
  /creative_works/related:
    get:
      summary: Related Creative Works
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _embedded:
                    type: object
                    properties:
                      creative_works:
                        type: array
                        items:
                          $ref: ./browse_manager.v1.yaml#/components/schemas/CreativeWork
                  _links:
                    $ref: ../models/HalLinks.v1.yaml
                  discover_guid:
                    type: string
                    description: Discover GUID used for interactions context
                  total_count:
                    type: integer
                    description: Total number of results
                required:
                  - _links
                  - discover_guid
                  - total_count
              examples:
                '1':
                  value:
                    _embedded:
                      creative_works:
                        - _links:
                            availabilities:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/availabilities
                            content_ratings:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/content_ratings
                            contributors:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/contributors
                            episodes:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/episodes
                            seasons:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/seasons
                            self:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46
                            tags:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/tags
                          artworks:
                            - height: 100
                              metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: poster
                              url: 'https://mydomain.com/poster.jpg'
                              width: 100
                          created_at: '2020-01-01T00:00:10Z'
                          deleted: false
                          descriptions:
                            - description: 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.'
                              metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: full
                          guid: 27c13eec19014084a0a3173061702b46
                          identifiers:
                            - id: '1'
                              source: mysource
                          relationships:
                            - href: /content/creative_works/eac7cb1192264b088ccbad0874395ce5
                              rel: parent
                          titles:
                            - metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: official
                              title: The Usual Suspects
                          type: movie
                          updated_at: '2020-01-01T00:00:10Z'
                    _links:
                      first:
                        href: /content/creative_works
                      last:
                        href: /content/creative_works?after_guid=8703dd1ced974ecea01116f2c0a5a282&limit=50
                      next:
                        href: /content/creative_works?after_guid=8703dd1ced974ecea01116f2c0a5a282&limit=50
                      prev:
                        href: /content/creative_works
                      self:
                        href: /content/creative_works?after_guid=8703dd1ced974ecea01116f2c0a5a282&limit=50
                    discover_guid: 8b63dd1ced974ecea01116f2c0a5a282
                    total_count: 1
      operationId: v1.discover.related.get
      parameters:
        - schema:
            type: string
          in: query
          name: content.id
          description: Id of the item to which items should be related
        - schema:
            type: string
          in: query
          name: content.source
          description: Namespace for seed_source_id so that consumers don't need to map to Utelly create_work_guid
        - schema:
            type: string
          in: header
          name: Content-Language
          description: 'Used to remove unnecessary titles, descriptions and artworks. Defaults to en-US'
        - schema:
            type: integer
          in: query
          name: limit
          description: Max items to be included in response
        - schema:
            type: integer
          in: query
          name: skip
          description: 'Number of items to skip, can be used with limit to page'
        - schema:
            items:
              enum:
                - creative_works
              type: string
            type: array
            example:
              - creative_works
          in: query
          name: embed
          description: 'List of related resources to be embedded in creative works. Note: embedded resources will themselves be fully embedded.'
          style: pipeDelimited
        - schema:
            items:
              type: string
            type: array
          in: query
          name: fields
          description: List of resource fields to be including in the response.
        - schema:
            items:
              type: string
            type: array
          in: query
          description: Has availability for one or more of the listed location ids.
          name: locations
        - schema: {}
          in: query
          name: user
          description: Allows for results to be personalised based on historic user interactions
        - schema:
            type: array
            items:
              type: string
          in: query
          name: services
          description: Has one or more of the listed service ids as an availability.
        - schema:
            type: array
            items:
              type: string
          in: query
          name: services.excl
          description: Has none of the listed service ids as an availability.
      description: ''
    parameters: []
components:
  schemas:
    user_object:
      title: user_object
      type: object
      properties:
        id:
          type: string
        source:
          type: string
    service_name:
      type: string
      title: service_name
      enum:
        - primevideo
        - netflix
        - disneyplus
  parameters:
    user_param:
      name: user
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/user_object'
      description: Allows for results to be personalised based on historic user interactions
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
