components:
  schemas:
    sample_statistics:
      type: object
      x-examples:
        '1':
          total_samples: 50
          total_verified: 45
          false_positive_count: 2
          false_negative_count: 1
      properties:
        total_shows_in_source:
          type: integer
        verified_shows_in_source:
          type: integer
        total_false_positives:
          type: integer
        total_false_negatives:
          type: integer
        verified_false_positives:
          type: integer
        verified_false_negatives:
          type: integer
    match:
      type: object
      properties:
        deleted:
          type: boolean
        destination_name:
          type: string
        destination_uid:
          type: string
        matcher:
          type: string
        source_name:
          type: string
        source_uid:
          type: string
      x-examples:
        '1':
          deleted: true
          destination_name: gracenote_gracenote
          destination_uid: '3232'
          matcher: ManualMatcher
          source_name: iva_iva
          source_uid: '123'
info:
  contact:
    email: developers@utelly.com
    name: API Support
  description: Api to manage DM0 entities
  title: dm0
  version: v1
openapi: 3.0.0
paths:
  '/data_matches/{type}':
    get:
      operationId: v1.data_matches.get
      parameters:
        - in: query
          name: group_uid
          required: true
          schema:
            type: string
        - in: query
          name: source
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                '1':
                  value:
                    items:
                      - deleted: true
                        destination_name: gracenote_gracenote
                        destination_uid: '3232'
                        matcher: ManualMatcher
                        source_name: iva_iva
                        source_uid: '123'
              schema:
                additionalProperties: false
                description: ''
                properties:
                  items:
                    items:
                      additionalProperties: false
                      properties:
                        deleted:
                          type: boolean
                        destination_name:
                          minLength: 1
                          type: string
                        destination_uid:
                          minLength: 1
                          type: string
                        matcher:
                          type: string
                        source_name:
                          minLength: 1
                          type: string
                        source_uid:
                          minLength: 1
                          type: string
                      required:
                        - source_name
                        - source_uid
                        - destination_name
                        - destination_uid
                        - deleted
                      type: object
                    minItems: 1
                    type: array
                    uniqueItems: true
                required:
                  - items
                type: object
          description: OK
      summary: Get data matches
      tags:
        - Dm0 Management
    parameters:
      - in: path
        name: type
        required: true
        schema:
          enum:
            - people
            - shows
          type: string
    post:
      operationId: v1.data_matches.post
      requestBody:
        content:
          application/json:
            examples:
              '1':
                value:
                  deleted: true
                  destination_name: gracenote_gracenote
                  destination_uid: '3232'
                  matcher: ManualMatcher
                  source_name: iva_iva
                  source_uid: '123'
            schema:
              additionalProperties: false
              description: ''
              properties:
                deleted:
                  type: boolean
                destination_name:
                  minLength: 1
                  type: string
                destination_uid:
                  minLength: 1
                  type: string
                matcher:
                  type: string
                source_name:
                  minLength: 1
                  type: string
                source_uid:
                  minLength: 1
                  type: string
              required:
                - source_name
                - source_uid
                - destination_name
                - destination_uid
                - deleted
                - matcher
              type: object
      responses:
        '201':
          content:
            application/json:
              examples:
                '1':
                  value:
                    deleted: true
                    destination_name: gracenote_gracenote
                    destination_uid: '3232'
                    matcher: ManualMatcher
                    source_name: iva_iva
                    source_uid: '123'
              schema:
                additionalProperties: false
                description: ''
                properties:
                  deleted:
                    type: boolean
                  destination_name:
                    minLength: 1
                    type: string
                  destination_uid:
                    minLength: 1
                    type: string
                  matcher:
                    type: string
                  source_name:
                    minLength: 1
                    type: string
                  source_uid:
                    minLength: 1
                    type: string
                required:
                  - source_name
                  - source_uid
                  - destination_name
                  - destination_uid
                  - deleted
                type: object
          description: Created
      summary: Create new data match
      tags:
        - Dm0 Management
  '/people/{uid}':
    get:
      operationId: v1.person.get
      parameters:
        - in: query
          name: source
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                '1':
                  value:
                    full_name: hello
                    pictures:
                      - url: 'https://mydomain.com/image.jpg'
                    uid: '23232'
              schema:
                additionalProperties: false
                description: ''
                properties:
                  full_name:
                    minLength: 1
                    type: string
                  pictures:
                    items:
                      additionalProperties: false
                      properties:
                        url:
                          minLength: 1
                          type: string
                      required:
                        - url
                      type: object
                    minItems: 1
                    type: array
                    uniqueItems: true
                  uid:
                    minLength: 1
                    type: string
                required:
                  - uid
                  - full_name
                  - pictures
                type: object
          description: OK
      summary: Get person
      tags:
        - Dm0 Management
    parameters:
      - in: path
        name: uid
        required: true
        schema:
          type: string
  '/shows/{uid}':
    get:
      operationId: v1.show.get
      parameters:
        - in: query
          name: source
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                '1':
                  value:
                    actors:
                      - full_name: Leonardo
                    pictures:
                      - url: 'https://mydomain.com/image.jpg'
                    primary_name: hello
                    uid: '23232'
              schema:
                additionalProperties: false
                description: ''
                properties:
                  actors:
                    items:
                      additionalProperties: false
                      properties:
                        full_name:
                          type: string
                      required:
                        - full_name
                      type: object
                    type: array
                  pictures:
                    items:
                      additionalProperties: false
                      properties:
                        url:
                          minLength: 1
                          type: string
                      required:
                        - url
                      type: object
                    minItems: 1
                    type: array
                    uniqueItems: true
                  primary_name:
                    minLength: 1
                    type: string
                  release_year:
                    type: integer
                  uid:
                    type: string
                required:
                  - primary_name
                  - pictures
                  - uid
                  - actors
                type: object
          description: OK
      summary: Get show
      tags:
        - Dm0 Management
    parameters:
      - in: path
        name: uid
        required: true
        schema:
          type: string
  '/data_quality/samples/{source}':
    get:
      summary: Fetch Sample
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sample_uid:
                    type: string
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        title_uid:
                          type: string
                        creative_work:
                          $ref: ./browse_manager.v1.yaml#/components/schemas/CreativeWork
                        matches:
                          type: array
                          items:
                            $ref: '#/components/schemas/match'
                  statistics:
                    $ref: '#/components/schemas/sample_statistics'
                  settings:
                    type: object
                    properties:
                      sample_uid:
                        type: string
                      show_types:
                        type: array
                        items:
                          type: string
                      exclude_verified:
                        type: boolean
                      count:
                        type: number
                      embed:
                        type: array
                        items:
                          type: string
              examples:
                '1':
                  value:
                    sample_uid: abc123
                    items:
                      - title_uid: 27c13eec19014084a0a3173061702b46
                        creative_work:
                          _links:
                            availabilities:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/availabilities
                            content_ratings:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/content_ratings
                            contributors:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/contributors
                            episodes:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/episodes
                            seasons:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/seasons
                            self:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46
                            tags:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/tags
                          artworks:
                            - height: 100
                              metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: poster
                              url: 'https://mydomain.com/poster.jpg'
                              width: 100
                          created_at: '2020-01-01T00:00:10Z'
                          deleted: false
                          descriptions:
                            - description: 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.'
                              metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: full
                          guid: 27c13eec19014084a0a3173061702b46
                          identifiers:
                            - id: '1'
                              source: mysource
                          relationships:
                            - href: /content/creative_works/eac7cb1192264b088ccbad0874395ce5
                              rel: parent
                          titles:
                            - metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: official
                              title: The Usual Suspects
                          type: movie
                          updated_at: '2020-01-01T00:00:10Z'
                        matches:
                          - deleted: true
                            destination_name: gracenote_gracenote
                            destination_uid: '3232'
                            matcher: ManualMatcher
                            source_name: iva_iva
                            source_uid: '123'
                    statistics:
                      total_shows_in_source: 500
                      verified_shows_in_source: 45
                      total_false_positives: 10
                      total_false_negatives: 6
                      verified_false_positives: 1
                      verified_false_negatives: 2
                    settings:
                      count: 1
                      embed:
                        - creative_works
      operationId: v1.data_quality.samples.get
      description: Retrieve a list of entities and their matches for review.
      tags:
        - Dm0 Management
      parameters:
        - schema:
            type: string
          in: query
          name: sample_uid
        - schema:
            type: array
            items:
              type: string
              enum:
                - tv
                - movie
                - series
          in: query
          name: show_types
          style: pipeDelimited
          description: Sample only shows of these types
        - schema:
            type: boolean
          in: query
          name: exclude_verified
          description: Sample only shows that are not verified
        - schema:
            type: integer
          in: query
          name: count
          description: Number of shows to sample
        - schema:
            type: array
            items:
              type: string
              enum:
                - creative_works
          in: query
          name: embed
          style: pipeDelimited
          description: Optionally include creative_works
    parameters:
      - schema:
          type: string
        name: source
        in: path
        required: true
        description: data source for sample
    post:
      summary: Create Sample
      operationId: v1.data_quality.samples.post
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  sample_uid:
                    type: string
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        title_uid:
                          type: string
                        creative_work:
                          $ref: ./browse_manager.v1.yaml#/components/schemas/CreativeWork
                        matches:
                          type: array
                          items:
                            $ref: '#/components/schemas/match'
                  statistics:
                    $ref: '#/components/schemas/sample_statistics'
              examples:
                '1':
                  value:
                    sample_uid: 000006f0899a4db3cba6bb76dccb551895db5445
                    items:
                      - title_uid: 27c13eec19014084a0a3173061702b46
                        creative_work:
                          _links:
                            availabilities:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/availabilities
                            content_ratings:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/content_ratings
                            contributors:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/contributors
                            episodes:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/episodes
                            seasons:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/seasons
                            self:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46
                            tags:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/tags
                          artworks:
                            - height: 100
                              metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: poster
                              url: 'https://mydomain.com/poster.jpg'
                              width: 100
                          created_at: '2020-01-01T00:00:10Z'
                          deleted: false
                          descriptions:
                            - description: 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.'
                              metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: full
                          guid: 27c13eec19014084a0a3173061702b46
                          identifiers:
                            - id: '1'
                              source: mysource
                          relationships:
                            - href: /content/creative_works/eac7cb1192264b088ccbad0874395ce5
                              rel: parent
                          titles:
                            - metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: official
                              title: The Usual Suspects
                          type: movie
                          updated_at: '2020-01-01T00:00:10Z'
                        matches:
                          - deleted: true
                            destination_name: gracenote_gracenote
                            destination_uid: '3232'
                            matcher: ManualMatcher
                            source_name: iva_iva
                            source_uid: '123'
                    statistics:
                      total_shows_in_source: 500
                      verified_shows_in_source: 45
                      total_false_positives: 10
                      total_false_negatives: 6
                      verified_false_positives: 1
                      verified_false_negatives: 2
      description: Create a list of entities and their matches for review.
      tags:
        - Dm0 Management
      parameters:
        - schema:
            type: integer
          in: query
          name: count
          description: Number of items to include in sample
        - schema:
            type: array
            enum:
              - movie
              - series
              - tv
          in: query
          name: show_types
          style: pipeDelimited
          description: Sample will only include shows of these types if set
        - schema:
            type: boolean
          in: query
          name: exclude_verified
          description: Exclude already verified items from sample
        - schema:
            type: boolean
          in: query
          name: replace_extant
          description: When set true any existing samples will be deleted
    delete:
      summary: Delete Sample
      operationId: v1.data_quality.samples.delete
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sample_uid:
                    type: string
                  deleted_count:
                    type: integer
              examples:
                '1':
                  value:
                    sample_uid: abc123
                    deleted_count: 50
      description: Delete a list of entities and their matches for review.
      parameters:
        - schema:
            type: string
          in: query
          name: sample_uid
          required: true
      tags:
        - Dm0 Management
  /data_quality/verify:
    parameters: []
    post:
      summary: Verify
      operationId: v1.data_quality.verify.post
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
                  verified:
                    type: boolean
                  statistics:
                    $ref: '#/components/schemas/sample_statistics'
              examples:
                '1':
                  value:
                    verified: true
                    uid: abc123
                    statistics:
                      total_shows_in_source: 500
                      verified_shows_in_source: 45
                      total_false_positives: 10
                      total_false_negatives: 6
                      verified_false_positives: 1
                      verified_false_negatives: 2
      tags:
        - Dm0 Management
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                verified:
                  type: boolean
                false_positive_count:
                  type: integer
                false_negative_count:
                  type: integer
              required:
                - verified
            examples:
              '1':
                value:
                  verified: true
                  false_positive_count: 0
                  false_negative_count: 2
        description: ''
      description: Verify that the specified item is correctly matched or unmatched. If flagged as incorrcect the optionally include guids of items to match or unmatch.
      parameters:
        - schema:
            type: string
          in: query
          name: uid
          required: true
          description: Show uid
        - schema:
            type: string
          in: query
          name: sample_uid
          description: Sample uid
        - schema:
            type: string
          in: query
          name: source
          required: true
          description: Data source
  '/data_quality/statistics/{source}':
    get:
      summary: Statistics
      tags:
        - Dm0 Management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sample_statistics'
              examples:
                '1':
                  value:
                    total_shows_in_source: 0
                    verified_shows_in_source: 0
                    total_false_positives: 0
                    total_false_negatives: 0
                    verified_false_positives: 0
                    verified_false_negatives: 0
      operationId: v1.data_quality.statistics.get
    parameters:
      - schema:
          type: string
        name: source
        in: path
        required: true
  "/explainer_tool/related/{source}":
    get:
      summary: explain
      operationId: v1.explainer_tool.related.get
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    seed_guid:
                      type: string
                    seed_title:
                      type: string
                    seed_source_id:
                      type: string
                    model:
                      type: object
                      properties:
                        name:
                          type: string
                        settings:
                          type: object
                          properties:
                            weights:
                              type: object
                    results:
                      type: array
                      items:
                        type: object
                        properties:
                          guid:
                            type: string
                          source_id:
                            type: string
                          title:
                            type: string
                          score:
                            type: number
                          components:
                            type: object
                          message:
                            type: string

                x-examples:
                  Example 1:
                    - seed_guid: ff10011d550d10513ab0d8fb76fe17a7060136f8
                      seed_title: "lego dc: shazam! magic and monsters"
                      seed_source_id: "shazam"
                      model:
                        name: tfidf
                        settings:
                          weights:
                            description: 0.05
                            tags: 0.25
                            title: 0.7
                      results:
                        - guid: 25346266de484d0eaf168d4e416434fdc6edfde1
                          title: "lego dc: shazam! magic and monsters"
                          source_id: "shazam"
                          score: 0.8138144818129545
                          components:
                            description: 1
                            tags: 0.25525792725181806
                            title: 1
                          message: 0.7*1.0 + 0.25*0.25525792725181806 + 0.05*1.0 = 0.8138144818129545
                        - guid: df7741b11aba8f3fb5dde3a77d1c54ba4dd7ab02
                          title: "lego dc super hero girls: super-villain high"
                          source_id: "legodcgirls"
                          score: 0.3365560651083932
                          components:
                            description: 0.11786247585439169
                            tags: 1
                            title: 0.08104664020637997
                          message: 0.7*0.11786247585439169 + 0.25*1.0 + 0.05*0.08104664020637997 = 0.3365560651083932
                        - guid: fb2710f34c97d57a3e7a12eec7ff4336c3493c2f
                          title: "jla adventures: trapped in time"
                          source_id: "jlaadventures"
                          score: 0.3159509456799562
                          components:
                            description: 0.0942156366856517
                            tags: 1
                            title: 0
                          message: 0.7*0.0942156366856517 + 0.25*1.0 + 0.05*0.0 = 0.3159509456799562
                        - guid: 7e01c5021c1c54762c157244a8e7fd7db51ee78b
                          title: "lego batman: the movie - dc super heroes unite"
                          source_id: "legobatman"
                          score: 0.29625431287660015
                          components:
                            description: 0.05934299763416806
                            tags: 1
                            title: 0.09428429065364974
                          message: 0.7*0.05934299763416806 + 0.25*1.0 + 0.05*0.09428429065364974 = 0.29625431287660015
                        - guid: 9a8d703dbbf73ed30ba362721670ae570c64e8de
                          title: "lego dc comics super heroes: aquaman - rage of atlantis"
                          source_id: "legodcaquaman"
                          score: 0.29566899918453904
                          components:
                            description: 0.05945620030096166
                            tags: 1
                            title: 0.08099317947731766
                          message: 0.7*0.05945620030096166 + 0.25*1.0 + 0.05*0.08099317947731766 = 0.29566899918453904
              examples:
                "1":
                  value:
                    - seed_guid: ff10011d550d10513ab0d8fb76fe17a7060136f8
                      seed_title: "lego dc: shazam! magic and monsters"
                      seed_source_id: "shazam"
                      model:
                        name: tfidf
                        settings:
                          weights:
                            description: 0.05
                            tags: 0.25
                            title: 0.7
                      results:
                        - guid: 25346266de484d0eaf168d4e416434fdc6edfde1
                          title: "lego dc: shazam! magic and monsters"
                          source_id: "shazam"
                          score: 0.8138144818129545
                          components:
                            description: 1
                            tags: 0.25525792725181806
                            title: 1
                          message: 0.7*1.0 + 0.25*0.25525792725181806 + 0.05*1.0 = 0.8138144818129545
                        - guid: df7741b11aba8f3fb5dde3a77d1c54ba4dd7ab02
                          title: "lego dc super hero girls: super-villain high"
                          source_id: "legodcgirls"
                          score: 0.3365560651083932
                          components:
                            description: 0.11786247585439169
                            tags: 1
                            title: 0.08104664020637997
                          message: 0.7*0.11786247585439169 + 0.25*1.0 + 0.05*0.08104664020637997 = 0.3365560651083932
                        - guid: fb2710f34c97d57a3e7a12eec7ff4336c3493c2f
                          title: "jla adventures: trapped in time"
                          source_id: "jlaadventures"
                          score: 0.3159509456799562
                          components:
                            description: 0.0942156366856517
                            tags: 1
                            title: 0
                          message: 0.7*0.0942156366856517 + 0.25*1.0 + 0.05*0.0 = 0.3159509456799562
                        - guid: 7e01c5021c1c54762c157244a8e7fd7db51ee78b
                          title: "lego batman: the movie - dc super heroes unite"
                          source_id: "legobatman"
                          score: 0.29625431287660015
                          components:
                            description: 0.05934299763416806
                            tags: 1
                            title: 0.09428429065364974
                          message: 0.7*0.05934299763416806 + 0.25*1.0 + 0.05*0.09428429065364974 = 0.29625431287660015
                        - guid: 9a8d703dbbf73ed30ba362721670ae570c64e8de
                          title: "lego dc comics super heroes: aquaman - rage of atlantis"
                          source_id: "legodcaquaman"
                          score: 0.29566899918453904
                          components:
                            description: 0.05945620030096166
                            tags: 1
                            title: 0.08099317947731766
                          message: 0.7*0.05945620030096166 + 0.25*1.0 + 0.05*0.08099317947731766 = 0.29566899918453904
    parameters:
      - schema:
          type: string
        name: source
        in: path
        required: true
      - schema:
          type: string
        in: query
        name: seed_guid
        required: true
  "/override/{source}/{creative_work_guid}/artworks":
    get:
      summary: Get all overridden artworks with their tags by creative_work_guid
      operationId: v1.override.artworks.get_all_artworks_tags_overridden
      responses:
        "200":
          description: OK1
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    guid:
                      type: string
                    uri:
                      type: string
                    tags:
                      type: array
                      items:
                        type: object
                        properties:
                          tag_guid:
                            type: string
                          name:
                            type: string
                          artwork_fitted_uri:
                            type: string
                          manually_created:
                            type: boolean
                          manually_overriden:
                            type: boolean
              examples:
                "1":
                  value:
                    - guid: c2cc6c3cd1ea3610e66adcad8b555eda50f7342e
                      uri: https://utellyassets4-7.imgix.net/assets/p18379525_v_v10_ab.jpg?fit=crop&auto=compress&crop=faces,top
                      tags:
                        - tag_guid: e287f931b467014a4fed48ded97d7887a62af2ba
                          name: poster
                          artwork_fitted_uri: https://utellyassets4-7.imgix.net/assets/p18379525_v_v10_ab.jpg?h=266&w=177&fit=crop&crop=faces,edges
                          manually_created: False
                          manually_overriden: True
                    - guid: 3232debd8274eed8d97751895fdd7ef21f5d32b3
                      uri: https://utelly2.global.ssl.fastly.net/00b5d9c750b094118928026deed8706f/https%3A%2F%2Fstatic.bb-static.com%2Fshain%2Fv1%2Fdataservice%2FResizeImage%2F%24value%3FFormat%3D%27jpg%27%26Quality%3D85%26ImageId%3D%27312060%27%26EntityType%3D%27Item%27%26EntityId%3D%2754216%27%26Width%3D720%26Height%3D1080%26ImageUrl%3D312060.jpg%26device%3Dweb_browser
                      tags:
                        - tag_guid: e287f931b467014a4fed48ded97d7887a62af2ba
                          name: billboard
                          artwork_fitted_uri: https://utelly2.global.ssl.fastly.net/00b5d9c750b094118928026deed8706f/https%3A%2F%2Fstatic.bb-static.com%2Fshain%2Fv1%2Fdataservice%2FResizeImage%2F%24value%3FFormat%3D%27jpg%27%26Quality%3D85%26ImageId%3D%27312060%27%26EntityType%3D%27Item%27%26EntityId%3D%2754216%27%26Width%3D720%26Height%3D1080%26ImageUrl%3D312060.jpg%26device%3Dweb_browser?h=266&w=177&fit=crop&crop=faces,edges
                          manually_created: False
                          manually_overriden: True
    parameters:
      - schema:
          type: string
        name: source
        in: path
        required: true
      - schema:
          type: string
        name: creative_work_guid
        in: path
        required: true
      - schema:
          type: boolean
        name: only_overridden
        in: query
        required: False
  "/override/{source}/{creative_work_guid}/artworks/{artwork_guid}":
    get:
      summary: Get artwork tags
      operationId: v1.override.artworks.get_artwork_tags
      responses:
        "200":
          description: OK1
          content:
            application/json:
              schema:
                type: object
                properties:
                  guid:
                    type: string
                  uri:
                    type: string
                  tags:
                    type: array
                    items:
                      type: object
                      properties:
                        tag_guid:
                          type: string
                        name:
                          type: string
                        artwork_fitted_uri:
                          type: string
                        manually_created:
                          type: boolean
                        manually_overriden:
                          type: boolean
              examples:
                "1":
                  value:
                    guid: c2cc6c3cd1ea3610e66adcad8b555eda50f7342e
                    uri: https://utellyassets4-7.imgix.net/assets/p18379525_v_v10_ab.jpg?fit=crop&auto=compress&crop=faces,top
                    tags:
                      - tag_guid: e287f931b467014a4fed48ded97d7887a62af2ba
                        name: poster
                        artwork_fitted_uri: https://utellyassets4-7.imgix.net/assets/p18379525_v_v10_ab.jpg?h=266&w=177&fit=crop&crop=faces,edges
                        manually_created: False
                        manually_overriden: True
    post:
      summary: Manually assign a new tag to artwork 
      operationId: v1.override.artworks.override_artwork_with_tag
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  tag_guid:
                    type: string
                  name:
                    type: string
                  artwork_fitted_uri:
                    type: string
                  manually_created:
                    type: boolean
                  manually_overriden:
                    type: boolean
              examples:
                "1":
                  value:
                    tag_guid: 00001d567eff55ce2d193bdfc786680734e25db1
                    name: main_poster
                    artwork_fitted_uri: https://utellyassets4-7.imgix.net/assets/p18379525_v_v10_ab.jpg?h=532&w=354&fit=crop
                    manually_created: True
                    manually_overriden: True
      description: Manually create a new tag and assign to an artwork with uri display parameters
      tags:
        - Dm0 Management
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                guid:
                  type: string
                name:
                  type: string
                uri_fit:
                  type: object
                  properties:
                    width:
                      type: integer
                    height:
                      type: integer
              required:
                - name
            examples:
              "1":
                value:
                  name: main_poster
                  uri_fit: 
                    width: 354
                    height: 532
    parameters:
      - schema:
          type: string
        name: source
        in: path
        required: true
      - schema:
          type: string
        name: artwork_guid
        in: path
        required: true
      - schema:
          type: string
        name: creative_work_guid
        in: path
        required: true
      - schema:
          type: boolean
        name: only_overridden
        in: query
        required: False
  "/override/{source}/{creative_work_guid}/artworks/{artwork_guid}/tags/{tag_guid}":
    delete:
      summary: Delete artwork tags override
      operationId: v1.override.artworks.delete_overridden_artwork_tag
      responses:
        '200':
          description: OK
      description: Delete a tag from an artwork
      tags:
        - Dm0 Management
    parameters:
      - schema:
          type: string
        name: source
        in: path
        required: true
      - schema:
          type: string
        name: artwork_guid
        in: path
        required: true
      - schema:
          type: string
        name: creative_work_guid
        in: path
        required: true
      - schema:
          type: string
        name: tag_guid
        in: path
        required: true
  "/override/{source}/artworks/tags":
    get:
      summary: Get available artwork tags
      operationId: v1.override.artworks.get_tags
      responses:
        "200":
          description: OK1
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    tag_guid:
                      type: string
                    name:
                      type: string
                    manually_created:
                      type: boolean
              examples:
                "1":
                  value:
                    - tag_guid: e287f931b467014a4fed48ded97d7887a62af2ba
                      name: poster
                      manually_created: False
                    - guid: 00001d567eff55ce2d193bdfc786680734e25db1
                      tag_guid: main_poster
                      manually_created: True
    parameters:
      - schema:
          type: string
        name: source
        in: path
        required: true

servers:
  - description: prod
    url: 'https://services.utelly.com/dm0_manager/v1'
  - description: staging
    url: 'https://staging-services.utelly.com/dm0_manager/v1'
  - description: dev
    url: 'https://dev-services.utelly.com/dm0_manager/v1'
tags:
  - name: utelly_services
